# Generated by Django 4.2.3 on 2023-10-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('nombre_comercial', models.CharField(blank=True, max_length=100)),
                ('ruc', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('direccion', models.CharField(blank=True, max_length=80)),
                ('ubigeo', models.CharField(blank=True, max_length=15)),
                ('gerente', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('urbanizacion', models.CharField(blank=True, max_length=60)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=60)),
                ('provincia', models.CharField(blank=True, max_length=60)),
                ('distrito', models.CharField(blank=True, max_length=60)),
                ('usuario_sunat', models.CharField(blank=True, max_length=15)),
                ('clave_sunat', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EnviarSunat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_porcentaje', models.IntegerField(default='18')),
            ],
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=5)),
                ('simbolo', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('codigoSunat', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('idEmpresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresaApp.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('numerocont', models.IntegerField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipocomprobante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresaApp.tipocomprobantes')),
            ],
        ),
    ]
