# Generated by Django 4.2.3 on 2023-10-29 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarioApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sunatApp', '0001_initial'),
        ('empresaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField(max_length=100)),
                ('cliente_doc', models.CharField(blank=True, max_length=15)),
                ('cliente_dir', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('numero', models.IntegerField(null=True)),
                ('igv_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idComprob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaApp.tipocomprobantes')),
                ('idMoneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresaApp.monedas')),
                ('idSucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresaApp.sucursal')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('serie', models.CharField(blank=True, max_length=5, null=True)),
                ('numComprobante', models.CharField(max_length=10)),
                ('metodoPago', models.CharField(max_length=20, null=True)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventaApp.pedidos')),
                ('idSucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresaApp.sucursal')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipComprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaApp.tipocomprobantes')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('umVenta', models.CharField(max_length=50, null=True)),
                ('proporcion', models.IntegerField(null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idAlmacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.almacen')),
                ('idPedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaApp.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=5)),
                ('numComprobante', models.CharField(blank=True, max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('codigoNC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sunatApp.codigonotacredito')),
                ('idVenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventaApp.ventas')),
                ('tipComprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaApp.tipocomprobantes')),
            ],
        ),
    ]
