# Generated by Django 4.2.3 on 2024-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdetalle',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
    ]
