# Generated by Django 4.2.3 on 2024-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0002_pedidosdetalle_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='dscto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
