# Generated by Django 4.2.3 on 2024-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0003_pedidos_dscto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='activo',
            field=models.IntegerField(null=True),
        ),
    ]
