# Generated by Django 4.2.3 on 2024-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0004_alter_ventas_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='activo',
            field=models.IntegerField(default=1),
        ),
    ]
