# Generated by Django 4.2.3 on 2024-04-08 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0002_pedidosdetalle_descuento'),
        ('sunatApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=5, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenDiarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idResDia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunatApp.resumendiario')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventaApp.ventas')),
            ],
        ),
    ]
